/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Max
 */
public class frmEditarVacante extends javax.swing.JFrame {

    /**
     * Creates new form frmEditarVacante
     */
    public frmEditarVacante() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TxtCodigo = new javax.swing.JTextField();
        TxtNombre = new javax.swing.JTextField();
        TxtSalario = new javax.swing.JTextField();
        TxtNumerov = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        CuadroDescripcion = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        BtnGrabar = new javax.swing.JButton();
        BtnCancelar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial Black", 3, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CODIGO:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(110, 80, 64, 18);

        jLabel2.setFont(new java.awt.Font("Arial Black", 3, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NOMBRE:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(110, 110, 69, 18);

        jLabel3.setFont(new java.awt.Font("Arial Black", 3, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("SALARIO:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(110, 150, 71, 18);

        jLabel4.setFont(new java.awt.Font("Arial Black", 3, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("NUMERO VACANTES:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 180, 156, 18);

        jLabel5.setFont(new java.awt.Font("Arial Black", 3, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("DESCRIPCION VACANTE:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(12, 222, 185, 18);
        getContentPane().add(TxtCodigo);
        TxtCodigo.setBounds(210, 80, 204, 19);
        getContentPane().add(TxtNombre);
        TxtNombre.setBounds(210, 110, 204, 19);
        getContentPane().add(TxtSalario);
        TxtSalario.setBounds(210, 150, 204, 19);
        getContentPane().add(TxtNumerov);
        TxtNumerov.setBounds(210, 180, 202, 19);

        CuadroDescripcion.setColumns(20);
        CuadroDescripcion.setRows(5);
        jScrollPane1.setViewportView(CuadroDescripcion);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(210, 220, 264, 140);

        jLabel6.setFont(new java.awt.Font("Arial Black", 3, 24)); // NOI18N
        jLabel6.setText("EDITAR VACANTE");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(119, 28, 276, 35);

        BtnGrabar.setText("GRABAR");
        getContentPane().add(BtnGrabar);
        BtnGrabar.setBounds(110, 380, 100, 25);

        BtnCancelar.setText("CANCELAR");
        getContentPane().add(BtnCancelar);
        BtnCancelar.setBounds(293, 380, 90, 25);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FondoRegistrar.jpg"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 490, 420);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmEditarVacante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmEditarVacante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmEditarVacante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmEditarVacante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmEditarVacante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BtnCancelar;
    public javax.swing.JButton BtnGrabar;
    public javax.swing.JTextArea CuadroDescripcion;
    public javax.swing.JTextField TxtCodigo;
    public javax.swing.JTextField TxtNombre;
    public javax.swing.JTextField TxtNumerov;
    public javax.swing.JTextField TxtSalario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
