/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Max
 */
public class frmMenuEmpleado extends javax.swing.JFrame {

    /**
     * Creates new form frmMenuEmpleado
     */
    public frmMenuEmpleado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BtnCrearVacante = new javax.swing.JButton();
        BtnMostrarPostulantes = new javax.swing.JButton();
        BtnEvaluar = new javax.swing.JButton();
        BtnSalir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial Black", 3, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MENU DE EMPLEADO DE RRHH");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 50, 380, 29);

        BtnCrearVacante.setFont(new java.awt.Font("Arial Black", 3, 10)); // NOI18N
        BtnCrearVacante.setText("CREAR VACANTES");
        getContentPane().add(BtnCrearVacante);
        BtnCrearVacante.setBounds(120, 110, 192, 25);

        BtnMostrarPostulantes.setFont(new java.awt.Font("Arial Black", 3, 10)); // NOI18N
        BtnMostrarPostulantes.setText("MOSTRAR POSTULANTES");
        getContentPane().add(BtnMostrarPostulantes);
        BtnMostrarPostulantes.setBounds(120, 160, 192, 25);

        BtnEvaluar.setFont(new java.awt.Font("Arial Black", 3, 10)); // NOI18N
        BtnEvaluar.setForeground(new java.awt.Color(255, 255, 255));
        BtnEvaluar.setText("EVALUAR POSTULANTES");
        getContentPane().add(BtnEvaluar);
        BtnEvaluar.setBounds(120, 209, 192, 25);

        BtnSalir.setFont(new java.awt.Font("Arial Black", 3, 10)); // NOI18N
        BtnSalir.setText("SALIR");
        getContentPane().add(BtnSalir);
        BtnSalir.setBounds(180, 320, 82, 25);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FondoRegistrar.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 430, 390);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenuEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenuEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenuEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenuEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenuEmpleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BtnCrearVacante;
    public javax.swing.JButton BtnEvaluar;
    public javax.swing.JButton BtnMostrarPostulantes;
    public javax.swing.JButton BtnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
